package MoviesPackage;

public class MoviesMB {

///--------------------------------------------------------------Initialize variables -------------------------------------------------------------------------------

	private String nameofMovie = "";
	private String director = "";
	private int minutes = 0;
	private double rating = 0.0;
	private int rottenTomatoScore = 0;
	//String[] stringArray = {"value1", "value2", "value3"};
	//String[] stringArray = new String[3];
	private Actor[] actorlist = new Actor[100];
	private int numofActors = 0;
		
	
///--------------------------------------------------------------Constructors -------------------------------------------------------------------------------
	
public MoviesMB() {  //Default Constructor (typed out)
		this.nameofMovie = "";
		this.director = "";
		this.minutes = 0;
		this.rating = 0;
		this.rottenTomatoScore = 0;
		this.numofActors = 0;
		
	}



public MoviesMB(String nameofMovie, String director, int minutes, double rating, int rottenTomatoScore, int numofActors) {  //Autogenerated Constructor //argument constructor
	super();
	this.nameofMovie = nameofMovie;
	this.director = director;
	this.minutes = minutes;
	this.rating = rating;
	this.rottenTomatoScore = rottenTomatoScore;
	this.numofActors = numofActors;
	this.actorlist = Actor(numofActors);
}


///------------------------------------------------------------Getters and Setters --------------------------------------------------------------------
public String getNameofMovie() {
	return nameofMovie;
}

public void setNameofMovie(String nameofMovie) {
	this.nameofMovie = nameofMovie;
}

public String getDirector() {
	return director;
}

public void setDirector(String director) {
	this.director = director;
}

public int getMinutes() {
	return minutes;
}

public void setMinutes(int minutes) {
	this.minutes = minutes;
}

public double getRating() {
	return rating;
}

public void setRating(double rating) {
	this.rating = rating;
}

public int getRottenTomatoScore() {
	return rottenTomatoScore;
}

public void setRottenTomatoScore(int rottenTomatoScore) {
	this.rottenTomatoScore = rottenTomatoScore;
}




public int getNumofActors() {
	return numofActors;
}




public void setNumofActors(int numofActors) {
	this.numofActors = numofActors;
}




public Actor[] getActorlist() {
	return actorlist;
}




public void setActorlist(Actor[] actorlist) {
	this.actorlist = actorlist;
}






///--------------------------------------------------------------toString method for printing -----------------------------------------------------------

@Override
public String toString() {
	//return "MoviesMB [nameofMovie=" + nameofMovie + ", director=" + director + ", minutes=" + minutes + ", rating="
	//		+ rating + ", rottenTomatoScore=" + rottenTomatoScore + "]";
//	return String.format("The movie %s was directed by %s and runs for %d minutes long.\n"
//			+ "Overall %s was given a rating of %.2f and a Rotten Tomato score of %d.", nameofMovie, director, minutes, nameofMovie, rating, rottenTomatoScore);
	return String.format("\nMovie name: %s \n"
			+ "Directed by: %s \n"
			+ "Run-time: %d minutes\n"
			+ "Rating: %.2f \n"
			+ "Rotten Tomato score: %d\n"
			+ "Number of Actors: %d\n\n", nameofMovie, director, minutes, rating, rottenTomatoScore, numofActors);	
}
	


}//end class
